<b>ССЫЛКА НА ДАШБОРД:</b><br>
http://redash.public.karpov.courses/public/dashboards/QWrIwGioPpEqdgbkgURu9shdDxv93q4NInLnW3Zv?org_slug=default

- CAC для двух рекламных кампаний

In [ ]:
with ad_c as(SELECT case when user_id in (8631, 8632, 8638, 8643, 8657, 8673, 8706, 8707, 8715,
                                          8723, 8732, 8739, 8741, 8750, 8751, 8752, 8770, 8774,
                                          8788, 8791, 8804, 8810, 8815, 8828, 8830, 8845, 8853,
                                          8859, 8867, 8869, 8876, 8879, 8883, 8896, 8909, 8911,
                                          8933, 8940, 8972, 8976, 8988, 8990, 9002, 9004, 9009,
                                          9019, 9020, 9035, 9036, 9061, 9069, 9071, 9075, 9081,
                                          9085, 9089, 9108, 9113, 9144, 9145, 9146, 9162, 9165,
                                          9167, 9175, 9180, 9182, 9197, 9198, 9210, 9223, 9251,
                                          9257, 9278, 9287, 9291, 9313, 9317, 9321, 9334, 9351,
                                          9391, 9398, 9414, 9420, 9422, 9431, 9450, 9451, 9454,
                                          9472, 9476, 9478, 9491, 9494, 9505, 9512, 9518, 9524,
                                          9526, 9528, 9531, 9535, 9550, 9559, 9561, 9562, 9599,
                                          9603, 9605, 9611, 9612, 9615, 9625, 9633, 9652, 9654,
                                          9655, 9660, 9662, 9667, 9677, 9679, 9689, 9695, 9720,
                                          9726, 9739, 9740, 9762, 9778, 9786, 9794, 9804, 9810,
                                          9813, 9818, 9828, 9831, 9836, 9838, 9845, 9871, 9887,
                                          9891, 9896, 9897, 9916, 9945, 9960, 9963, 9965, 9968,
                                          9971, 9993, 9998, 9999, 10001, 10013, 10016, 10023, 10030,
                                          10051, 10057, 10064, 10082, 10103, 10105, 10122, 10134,
                                          10135) then 'Кампания № 1'
                         when user_id in (8629, 8630, 8644, 8646, 8650, 8655, 8659, 8660, 8663, 8665, 8670,
                                          8675, 8680, 8681, 8682, 8683, 8694, 8697, 8700, 8704,
                                          8712, 8713, 8719, 8729, 8733, 8742, 8748, 8754, 8771,
                                          8794, 8795, 8798, 8803, 8805, 8806, 8812, 8814, 8825,
                                          8827, 8838, 8849, 8851, 8854, 8855, 8870, 8878, 8882,
                                          8886, 8890, 8893, 8900, 8902, 8913, 8916, 8923, 8929,
                                          8935, 8942, 8943, 8949, 8953, 8955, 8966, 8968, 8971,
                                          8973, 8980, 8995, 8999, 9000, 9007, 9013, 9041, 9042,
                                          9047, 9064, 9068, 9077, 9082, 9083, 9095, 9103, 9109,
                                          9117, 9123, 9127, 9131, 9137, 9140, 9149, 9161, 9179,
                                          9181, 9183, 9185, 9190, 9196, 9203, 9207, 9226, 9227,
                                          9229, 9230, 9231, 9250, 9255, 9259, 9267, 9273, 9281,
                                          9282, 9289, 9292, 9303, 9310, 9312, 9315, 9327, 9333,
                                          9335, 9337, 9343, 9356, 9368, 9370, 9383, 9392, 9404,
                                          9410, 9421, 9428, 9432, 9437, 9468, 9479, 9483, 9485,
                                          9492, 9495, 9497, 9498, 9500, 9510, 9527, 9529, 9530,
                                          9538, 9539, 9545, 9557, 9558, 9560, 9564, 9567, 9570,
                                          9591, 9596, 9598, 9616, 9631, 9634, 9635, 9636, 9658,
                                          9666, 9672, 9684, 9692, 9700, 9704, 9706, 9711, 9719,
                                          9727, 9735, 9741, 9744, 9749, 9752, 9753, 9755, 9757,
                                          9764, 9783, 9784, 9788, 9790, 9808, 9820, 9839, 9841,
                                          9843, 9853, 9855, 9859, 9863, 9877, 9879, 9880, 9882,
                                          9883, 9885, 9901, 9904, 9908, 9910, 9912, 9920, 9929,
                                          9930, 9935, 9939, 9958, 9959, 9961, 9983, 10027, 10033,
                                          10038, 10045, 10047, 10048, 10058, 10059, 10067, 10069,
                                          10073, 10075, 10078, 10079, 10081, 10092, 10106, 10110,
                                          10113, 10131) then 'Кампания № 2' end as ads_campaign,
                    count(distinct user_id) as user_count
             FROM user_actions
             WHERE order_id not in (SELECT order_id
                                     FROM   user_actions
                                     WHERE  action = 'cancel_order')
             GROUP BY ads_campaign)

SELECT ads_campaign,
       round(250000 / user_count::decimal, 2) as cac
FROM ad_c
WHERE ads_campaign is not null
ORDER BY cac desc

- ROI для каждого рекламного канала

In [ ]:
with ad_c as(
SELECT case when user_id in (8631, 8632, 8638, 8643, 8657, 8673, 8706, 8707, 8715,
                             8723, 8732, 8739, 8741, 8750, 8751, 8752, 8770, 8774,
                             8788, 8791, 8804, 8810, 8815, 8828, 8830, 8845, 8853,
                             8859, 8867, 8869, 8876, 8879, 8883, 8896, 8909, 8911,
                             8933, 8940, 8972, 8976, 8988, 8990, 9002, 9004, 9009,
                             9019, 9020, 9035, 9036, 9061, 9069, 9071, 9075, 9081,
                             9085, 9089, 9108, 9113, 9144, 9145, 9146, 9162, 9165,
                             9167, 9175, 9180, 9182, 9197, 9198, 9210, 9223, 9251,
                             9257, 9278, 9287, 9291, 9313, 9317, 9321, 9334, 9351,
                             9391, 9398, 9414, 9420, 9422, 9431, 9450, 9451, 9454,
                             9472, 9476, 9478, 9491, 9494, 9505, 9512, 9518, 9524,
                             9526, 9528, 9531, 9535, 9550, 9559, 9561, 9562, 9599,
                             9603, 9605, 9611, 9612, 9615, 9625, 9633, 9652, 9654,
                             9655, 9660, 9662, 9667, 9677, 9679, 9689, 9695, 9720,
                             9726, 9739, 9740, 9762, 9778, 9786, 9794, 9804, 9810,
                             9813, 9818, 9828, 9831, 9836, 9838, 9845, 9871, 9887,
                             9891, 9896, 9897, 9916, 9945, 9960, 9963, 9965, 9968,
                             9971, 9993, 9998, 9999, 10001, 10013, 10016, 10023, 10030,
                             10051, 10057, 10064, 10082, 10103, 10105, 10122, 10134,
                                          10135) then 'Кампания № 1'
              when user_id in (8629, 8630, 8644, 8646, 8650, 8655, 8659, 8660, 8663, 8665, 8670,
                               8675, 8680, 8681, 8682, 8683, 8694, 8697, 8700, 8704,
                               8712, 8713, 8719, 8729, 8733, 8742, 8748, 8754, 8771,
                               8794, 8795, 8798, 8803, 8805, 8806, 8812, 8814, 8825,
                               8827, 8838, 8849, 8851, 8854, 8855, 8870, 8878, 8882,
                               8886, 8890, 8893, 8900, 8902, 8913, 8916, 8923, 8929,
                               8935, 8942, 8943, 8949, 8953, 8955, 8966, 8968, 8971,
                               8973, 8980, 8995, 8999, 9000, 9007, 9013, 9041, 9042,
                               9047, 9064, 9068, 9077, 9082, 9083, 9095, 9103, 9109,
                               9117, 9123, 9127, 9131, 9137, 9140, 9149, 9161, 9179,
                               9181, 9183, 9185, 9190, 9196, 9203, 9207, 9226, 9227,
                               9229, 9230, 9231, 9250, 9255, 9259, 9267, 9273, 9281,
                               9282, 9289, 9292, 9303, 9310, 9312, 9315, 9327, 9333,
                               9335, 9337, 9343, 9356, 9368, 9370, 9383, 9392, 9404,
                               9410, 9421, 9428, 9432, 9437, 9468, 9479, 9483, 9485,
                               9492, 9495, 9497, 9498, 9500, 9510, 9527, 9529, 9530,
                               9538, 9539, 9545, 9557, 9558, 9560, 9564, 9567, 9570,
                               9591, 9596, 9598, 9616, 9631, 9634, 9635, 9636, 9658,
                               9666, 9672, 9684, 9692, 9700, 9704, 9706, 9711, 9719,
                               9727, 9735, 9741, 9744, 9749, 9752, 9753, 9755, 9757,
                               9764, 9783, 9784, 9788, 9790, 9808, 9820, 9839, 9841,
                               9843, 9853, 9855, 9859, 9863, 9877, 9879, 9880, 9882,
                               9883, 9885, 9901, 9904, 9908, 9910, 9912, 9920, 9929,
                               9930, 9935, 9939, 9958, 9959, 9961, 9983, 10027, 10033,
                               10038, 10045, 10047, 10048, 10058, 10059, 10067, 10069,
                               10073, 10075, 10078, 10079, 10081, 10092, 10106, 10110,
                              10113, 10131) then 'Кампания № 2' end as ads_campaign,
                    user_id,
                    order_id
             FROM user_actions
             WHERE order_id not in (SELECT order_id
                                     FROM user_actions
                                     WHERE action = 'cancel_order')),

order_price as(
SELECT order_id,
       sum(price) as revenue
FROM (SELECT order_id,
             unnest(product_ids) as product_id
      FROM orders) as t1
join products using (product_id)
GROUP BY order_id)

SELECT ads_campaign,
       round(sum(revenue) / 250000.0 * 100 - 100, 2) as roi
FROM ad_c join order_price using(order_id)
WHERE ads_campaign is not null
GROUP BY ads_campaign
ORDER BY roi desc

- Средняя стоимость заказа привлечённых пользователей с 1 по 7 сентября 2022 года.

In [ ]:
with ad_c as(
SELECT case when user_id in (8631, 8632, 8638, 8643, 8657, 8673, 8706, 8707, 8715,
                             8723, 8732, 8739, 8741, 8750, 8751, 8752, 8770, 8774,
                             8788, 8791, 8804, 8810, 8815, 8828, 8830, 8845, 8853,
                             8859, 8867, 8869, 8876, 8879, 8883, 8896, 8909, 8911,
                             8933, 8940, 8972, 8976, 8988, 8990, 9002, 9004, 9009,
                             9019, 9020, 9035, 9036, 9061, 9069, 9071, 9075, 9081,
                             9085, 9089, 9108, 9113, 9144, 9145, 9146, 9162, 9165,
                             9167, 9175, 9180, 9182, 9197, 9198, 9210, 9223, 9251,
                             9257, 9278, 9287, 9291, 9313, 9317, 9321, 9334, 9351,
                             9391, 9398, 9414, 9420, 9422, 9431, 9450, 9451, 9454,
                             9472, 9476, 9478, 9491, 9494, 9505, 9512, 9518, 9524,
                             9526, 9528, 9531, 9535, 9550, 9559, 9561, 9562, 9599,
                             9603, 9605, 9611, 9612, 9615, 9625, 9633, 9652, 9654,
                             9655, 9660, 9662, 9667, 9677, 9679, 9689, 9695, 9720,
                             9726, 9739, 9740, 9762, 9778, 9786, 9794, 9804, 9810,
                             9813, 9818, 9828, 9831, 9836, 9838, 9845, 9871, 9887,
                             9891, 9896, 9897, 9916, 9945, 9960, 9963, 9965, 9968,
                             9971, 9993, 9998, 9999, 10001, 10013, 10016, 10023, 10030,
                             10051, 10057, 10064, 10082, 10103, 10105, 10122, 10134,
                                          10135) then 'Кампания № 1'
              when user_id in (8629, 8630, 8644, 8646, 8650, 8655, 8659, 8660, 8663, 8665, 8670,
                               8675, 8680, 8681, 8682, 8683, 8694, 8697, 8700, 8704,
                               8712, 8713, 8719, 8729, 8733, 8742, 8748, 8754, 8771,
                               8794, 8795, 8798, 8803, 8805, 8806, 8812, 8814, 8825,
                               8827, 8838, 8849, 8851, 8854, 8855, 8870, 8878, 8882,
                               8886, 8890, 8893, 8900, 8902, 8913, 8916, 8923, 8929,
                               8935, 8942, 8943, 8949, 8953, 8955, 8966, 8968, 8971,
                               8973, 8980, 8995, 8999, 9000, 9007, 9013, 9041, 9042,
                               9047, 9064, 9068, 9077, 9082, 9083, 9095, 9103, 9109,
                               9117, 9123, 9127, 9131, 9137, 9140, 9149, 9161, 9179,
                               9181, 9183, 9185, 9190, 9196, 9203, 9207, 9226, 9227,
                               9229, 9230, 9231, 9250, 9255, 9259, 9267, 9273, 9281,
                               9282, 9289, 9292, 9303, 9310, 9312, 9315, 9327, 9333,
                               9335, 9337, 9343, 9356, 9368, 9370, 9383, 9392, 9404,
                               9410, 9421, 9428, 9432, 9437, 9468, 9479, 9483, 9485,
                               9492, 9495, 9497, 9498, 9500, 9510, 9527, 9529, 9530,
                               9538, 9539, 9545, 9557, 9558, 9560, 9564, 9567, 9570,
                               9591, 9596, 9598, 9616, 9631, 9634, 9635, 9636, 9658,
                               9666, 9672, 9684, 9692, 9700, 9704, 9706, 9711, 9719,
                               9727, 9735, 9741, 9744, 9749, 9752, 9753, 9755, 9757,
                               9764, 9783, 9784, 9788, 9790, 9808, 9820, 9839, 9841,
                               9843, 9853, 9855, 9859, 9863, 9877, 9879, 9880, 9882,
                               9883, 9885, 9901, 9904, 9908, 9910, 9912, 9920, 9929,
                               9930, 9935, 9939, 9958, 9959, 9961, 9983, 10027, 10033,
                               10038, 10045, 10047, 10048, 10058, 10059, 10067, 10069,
                               10073, 10075, 10078, 10079, 10081, 10092, 10106, 10110,
                              10113, 10131) then 'Кампания № 2' end as ads_campaign,
                    user_id,
                    order_id,
                    time::date as date
             FROM user_actions
             WHERE order_id not in (SELECT order_id
                                     FROM user_actions
                                     WHERE action = 'cancel_order')
             and time::date between '2022-09-01'
             and '2022-09-07'),

order_prices as (
SELECT order_id,
       sum(price) as order_price
FROM (SELECT order_id,
             unnest(product_ids) as product_id
FROM orders
WHERE order_id not in (SELECT order_id
                       FROM user_actions
                       WHERE action = 'cancel_order')) as t1
join products using (product_id)
GROUP BY order_id)

SELECT ads_campaign,
       round(avg(avg_check), 2) as avg_check
FROM (SELECT ads_campaign,
             user_id,
             avg(order_price) as avg_check
        FROM ad_c join order_prices using (order_id)
        WHERE ads_campaign is not null
        and date between '2022-09-01' and '2022-09-07'
        GROUP BY ads_campaign, user_id) as t1
GROUP BY ads_campaign
ORDER BY avg_check desc

- Показатель дневного Retention

In [ ]:
SELECT start_month,
       start_date,
       day_number,
       round(users::decimal / lag(users, day_number) OVER(PARTITION BY start_month,
                                                    start_date), 2) as retention
FROM(SELECT start_month,
            start_date,
            time::date - start_date as day_number,
            count(distinct user_id) as users FROM(SELECT min(month) as start_month,
                                                         min(time::date) as start_date,
                                                         user_id FROM(SELECT date_trunc('month', time::date)::date as month,
                                                                             time,
                                                                             user_id
                                                                       FROM user_actions) as t1
                                                  GROUP BY user_id) as t2
     join user_actions using(user_id)
GROUP BY start_month, start_date, day_number) as t3
ORDER BY start_month, start_date, day_number

- Retention для двух групп пользователей

In [ ]:
SELECT ads_campaign,
       start_date,
       dt - start_date as day_number,
       round(count(distinct user_id)::numeric/max(count(distinct user_id)) OVER (PARTITION BY start_date,
                                                                                              ads_campaign), 2) as retention
FROM (SELECT case when user_id in (8804, 9828, 9524, 9667, 9165, 10013, 9625, 8879, 9145,
                                     8657, 8706, 9476, 9813, 8940, 9971, 10122, 8732, 9689,
                                     9198, 8896, 8815, 9689, 9075, 9071, 9528, 9896, 10135,
                                     9478, 9612, 8638, 10057, 9167, 9450, 9999, 9313, 9720,
                                     9599, 9351, 8638, 8752, 9998, 9431, 9660, 9004, 8632,
                                     8896, 8750, 9605, 8867, 9535, 9494, 9762, 8990, 9526,
                                     9786, 9654, 9144, 9391, 10016, 8988, 9009, 9061, 9004,
                                     9550, 8707, 8788, 8988, 8853, 9836, 8810, 9916, 9660,
                                     9677, 9896, 8933, 8828, 9108, 9180, 9897, 9960, 9472,
                                     9818, 9695, 9965, 10023, 8972, 9035, 8869, 9662, 9561,
                                     9740, 8723, 9146, 10103, 9963, 10103, 8715, 9167, 9313,
                                     9679, 9251, 10001, 8867, 8707, 9945, 9562, 10013, 9020,
                                     9317, 9002, 9838, 9144, 8911, 9505, 9313, 10134, 9197,
                                     9398, 9652, 9999, 9210, 8741, 9963, 9422, 9778, 8815,
                                     9512, 9794, 9019, 9287, 9561, 9321, 9677, 10122, 8752,
                                     9810, 9871, 9162, 8876, 9414, 10030, 9334, 9175, 9182,
                                     9451, 9257, 9321, 9531, 9655, 9845, 8883, 9993, 9804,
                                     10105, 8774, 8631, 9081, 8845, 9451, 9019, 8750, 8788,
                                     9625, 9414, 10064, 9633, 9891, 8751, 8643, 9559, 8791,
                                     9518, 9968, 9726, 9036, 9085, 9603, 8909, 9454, 9739,
                                     9223, 9420, 8830, 9615, 8859, 9887, 9491, 8739, 8770,
                                     9069, 9278, 9831, 9291, 9089, 8976, 9611, 10082, 8673,
                                     9113, 10051) then 'Кампания № 1'
                    when user_id in (9752, 9510, 8893, 9196, 10038, 9839, 9820, 9064, 9930, 9529, 9267,
                                     9161, 9231, 8953, 9863, 8878, 10078, 9370, 8675, 9961,
                                     9007, 9207, 9539, 9335, 8700, 9598, 9068, 9082, 8916,
                                     10131, 9704, 9904, 9421, 9083, 9337, 9041, 8955, 10033,
                                     9137, 9539, 8855, 9117, 8771, 9226, 8733, 8851, 9749,
                                     10027, 9757, 9788, 8646, 9567, 9140, 9719, 10073, 9000,
                                     8971, 9437, 9958, 8683, 9410, 10075, 8923, 9255, 8995,
                                     9343, 10059, 9082, 9267, 9929, 8670, 9570, 9281, 8795,
                                     9082, 8814, 8795, 10067, 9700, 9432, 9783, 10081, 9591,
                                     8733, 9337, 9808, 9392, 9185, 8882, 8681, 8825, 9692,
                                     10048, 8682, 9631, 8942, 9910, 9428, 9500, 9527, 8655,
                                     8890, 9000, 8827, 9485, 9013, 9042, 10047, 8798, 9250,
                                     8929, 9161, 9545, 9333, 9230, 9841, 8659, 9181, 9880,
                                     9983, 9538, 9483, 9557, 9883, 9901, 9103, 10110, 8827,
                                     9530, 9310, 9711, 9383, 9527, 8968, 8973, 9497, 9753,
                                     8980, 8838, 9370, 8682, 8854, 8966, 9658, 9939, 8704,
                                     9281, 10113, 8697, 9149, 8870, 9959, 9127, 9203, 9635,
                                     9273, 9356, 10069, 9855, 8680, 9912, 8900, 9131, 10058,
                                     9479, 9259, 9368, 9908, 9468, 8902, 9292, 8742, 9672,
                                     9564, 8949, 9404, 9183, 8913, 8694, 10092, 8771, 8805,
                                     8794, 9179, 9666, 9095, 9935, 9190, 9183, 9631, 9231,
                                     9109, 9123, 8806, 9229, 9741, 9303, 9303, 10045, 9744,
                                     8665, 9843, 9634, 8812, 9684, 9616, 8660, 9498, 9877,
                                     9727, 9882, 8663, 9755, 8754, 9131, 9273, 9879, 9492,
                                     9920, 9853, 8803, 9711, 9885, 9560, 8886, 8644, 9636,
                                     10073, 10106, 9859, 8943, 8849, 8629, 8729, 9227, 9711,
                                     9282, 9312, 8630, 9735, 9315, 9077, 8999, 8713, 10079,
                                     9596, 8748, 9327, 9790, 8719, 9706, 9289, 9047, 9495,
                                     9558, 8650, 9784, 8935, 9764, 8712) then 'Кампания № 2' end as ads_campaign,
               user_id,
               min(time::date) OVER (PARTITION BY user_id) as start_date,
               time::date as dt
        FROM user_actions) as camp_sq
WHERE ads_campaign is not null
and dt - start_date in (0, 1, 7)
GROUP BY ads_campaign, start_date, dt
ORDER BY ads_campaign, day_number

- Накопительный ARPPU и CAC

In [ ]:
with main_table as (SELECT ads_campaign,
                           user_id,
                           order_id,
                           time,
                           product_id,
                           price
                    FROM   (SELECT ads_campaign,
                                   user_id,
                                   order_id,
                                   time
                            FROM   (SELECT user_id,
                                           order_id,
                                           time,
                                           case when user_id in (8631, 8632, 8638, 8643, 8657, 8673, 8706, 8707, 8715, 8723, 8732,
                                                                 8739, 8741, 8750, 8751, 8752, 8770, 8774, 8788, 8791,
                                                                 8804, 8810, 8815, 8828, 8830, 8845, 8853, 8859, 8867,
                                                                 8869, 8876, 8879, 8883, 8896, 8909, 8911, 8933, 8940,
                                                                 8972, 8976, 8988, 8990, 9002, 9004, 9009, 9019, 9020,
                                                                 9035, 9036, 9061, 9069, 9071, 9075, 9081, 9085, 9089,
                                                                 9108, 9113, 9144, 9145, 9146, 9162, 9165, 9167, 9175,
                                                                 9180, 9182, 9197, 9198, 9210, 9223, 9251, 9257, 9278,
                                                                 9287, 9291, 9313, 9317, 9321, 9334, 9351, 9391, 9398,
                                                                 9414, 9420, 9422, 9431, 9450, 9451, 9454, 9472, 9476,
                                                                 9478, 9491, 9494, 9505, 9512, 9518, 9524, 9526, 9528,
                                                                 9531, 9535, 9550, 9559, 9561, 9562, 9599, 9603, 9605,
                                                                 9611, 9612, 9615, 9625, 9633, 9652, 9654, 9655, 9660,
                                                                 9662, 9667, 9677, 9679, 9689, 9695, 9720, 9726, 9739,
                                                                 9740, 9762, 9778, 9786, 9794, 9804, 9810, 9813, 9818,
                                                                 9828, 9831, 9836, 9838, 9845, 9871, 9887, 9891, 9896,
                                                                 9897, 9916, 9945, 9960, 9963, 9965, 9968, 9971, 9993,
                                                                 9998, 9999, 10001, 10013, 10016, 10023, 10030, 10051,
                                                                 10057, 10064, 10082, 10103, 10105, 10122, 10134, 10135) then 1
                                                when user_id in (8629, 8630, 8644, 8646, 8650, 8655, 8659, 8660, 8663, 8665, 8670,
                                                                 8675, 8680, 8681, 8682, 8683, 8694, 8697, 8700, 8704,
                                                                 8712, 8713, 8719, 8729, 8733, 8742, 8748, 8754, 8771,
                                                                 8794, 8795, 8798, 8803, 8805, 8806, 8812, 8814, 8825,
                                                                 8827, 8838, 8849, 8851, 8854, 8855, 8870, 8878, 8882,
                                                                 8886, 8890, 8893, 8900, 8902, 8913, 8916, 8923, 8929,
                                                                 8935, 8942, 8943, 8949, 8953, 8955, 8966, 8968, 8971,
                                                                 8973, 8980, 8995, 8999, 9000, 9007, 9013, 9041, 9042,
                                                                 9047, 9064, 9068, 9077, 9082, 9083, 9095, 9103, 9109,
                                                                 9117, 9123, 9127, 9131, 9137, 9140, 9149, 9161, 9179,
                                                                 9181, 9183, 9185, 9190, 9196, 9203, 9207, 9226, 9227,
                                                                 9229, 9230, 9231, 9250, 9255, 9259, 9267, 9273, 9281,
                                                                 9282, 9289, 9292, 9303, 9310, 9312, 9315, 9327, 9333,
                                                                 9335, 9337, 9343, 9356, 9368, 9370, 9383, 9392, 9404,
                                                                 9410, 9421, 9428, 9432, 9437, 9468, 9479, 9483, 9485,
                                                                 9492, 9495, 9497, 9498, 9500, 9510, 9527, 9529, 9530,
                                                                 9538, 9539, 9545, 9557, 9558, 9560, 9564, 9567, 9570,
                                                                 9591, 9596, 9598, 9616, 9631, 9634, 9635, 9636, 9658,
                                                                 9666, 9672, 9684, 9692, 9700, 9704, 9706, 9711, 9719,
                                                                 9727, 9735, 9741, 9744, 9749, 9752, 9753, 9755, 9757,
                                                                 9764, 9783, 9784, 9788, 9790, 9808, 9820, 9839, 9841,
                                                                 9843, 9853, 9855, 9859, 9863, 9877, 9879, 9880, 9882,
                                                                 9883, 9885, 9901, 9904, 9908, 9910, 9912, 9920, 9929,
                                                                 9930, 9935, 9939, 9958, 9959, 9961, 9983, 10027, 10033,
                                                                 10038, 10045, 10047, 10048, 10058, 10059, 10067, 10069,
                                                                 10073, 10075, 10078, 10079, 10081, 10092, 10106, 10110,
                                                                 10113, 10131) then 2
                                                else 0 end as ads_campaign,
                                           count(action) filter (WHERE action = 'cancel_order') OVER (PARTITION BY order_id) as is_canceled
                                    FROM user_actions) t1
                            WHEREads_campaign in (1, 2)
                            and is_canceled = 0) t2
                        LEFT JOIN (SELECT order_id,
                                          unnest(product_ids) as product_id
                                   FROM orders) t3 using (order_id)
                        LEFT JOIN products using (product_id))
SELECT concat('Кампания № ', ads_campaign) as ads_campaign,
       concat('Day ', row_number() OVER (PARTITION BY ads_campaign
                                         ORDER BY date) - 1) as day,
       round(sum(revenue) OVER (PARTITION BY ads_campaign
                                ORDER BY date) / paying_users::decimal, 2) as cumulative_arppu,
                                cac
FROM (SELECT ads_campaign,
             time::date as date,
             sum(price) as revenue
        FROM main_table
        GROUP BY ads_campaign, time::date) t1
    LEFT JOIN (SELECT ads_campaign,
                      count(distinct user_id) as paying_users,
                      round(250000.0 / count(distinct user_id), 2) as cac
               FROM main_table
               GROUP BY ads_campaign) t2 using (ads_campaign);